name = "zoharatkins-com"
main = "worker.js"
compatibility_date = "2026-06-16"

routes = [
  { pattern = "zoharatkins.com/*", zone_name = "zoharatkins.com" },
  { pattern = "www.zoharatkins.com/*", zone_name = "zoharatkins.com" }
]
